"""
record_environment.py
=====================
Write `requirements-lock.txt` and print a Markdown table of the exact package
versions present in the interpreter that runs this script.

The article states that the software environment is recorded with the released
artefacts. Run this in the environment that produced those artefacts, commit the
lock file, and paste the printed table into `docs/environment.md`. Do not hand
edit either one: a version string nobody measured is worse than no version
string at all, because it looks like evidence.

Usage
-----
    python scripts/record_environment.py
    python scripts/record_environment.py --out requirements-lock.txt
"""

import argparse
import importlib
import os
import platform
import sys

PACKAGES = [
    ('numpy', 'numpy'),
    ('pandas', 'pandas'),
    ('scipy', 'scipy'),
    ('scikit-learn', 'sklearn'),
    ('imbalanced-learn', 'imblearn'),
    ('xgboost', 'xgboost'),
    ('tensorflow', 'tensorflow'),
    ('PyWavelets', 'pywt'),
    ('wfdb', 'wfdb'),
    ('scikit-posthocs', 'scikit_posthocs'),
    ('statsmodels', 'statsmodels'),
    ('xlrd', 'xlrd'),
    ('openpyxl', 'openpyxl'),
]


def collect():
    rows = []
    for dist, module in PACKAGES:
        try:
            v = getattr(importlib.import_module(module), '__version__', None)
        except Exception:                                   # noqa: BLE001
            v = None
        rows.append((dist, v))
    return rows


def main(out):
    rows = collect()
    missing = [d for d, v in rows if v is None]

    header = [
        '# Exact versions of the environment that produced the published runs.',
        '# Generated by scripts/record_environment.py. Do not edit by hand.',
        f'# python {sys.version.split()[0]} on {platform.platform()}',
    ]
    lines = header + [f'{d}=={v}' for d, v in rows if v is not None]
    with open(out, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')

    print(f'wrote {out}\n')
    print('| package | version |')
    print('|---|---|')
    print(f'| python | {sys.version.split()[0]} |')
    for d, v in rows:
        print(f'| {d} | {v if v else "not installed"} |')

    try:
        import tensorflow as tf
        gpus = [g.name for g in tf.config.list_physical_devices('GPU')]
        print(f'\nGPU devices visible: {gpus or "none"}')
    except Exception:                                       # noqa: BLE001
        print('\nGPU devices visible: tensorflow not importable')

    if missing:
        print('\nNot installed here: ' + ', '.join(missing))
        print('This lock file is therefore incomplete. Re-run it in the '
              'environment that produced the published results.')
        return 1
    return 0


if __name__ == '__main__':
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--out', default=os.path.join(
        os.path.dirname(__file__), '..', 'requirements-lock.txt'))
    sys.exit(main(ap.parse_args().out))
